import { Category, WordEntry } from './types';

export const DICTIONARY_DATA: WordEntry[] = [
  // --- NUMBERS (Angka) ---
  // Satuan (1-10)
  { id: 'n1', indo: 'Satu', mee: 'Enaa', category: Category.NUMBERS },
  { id: 'n2', indo: 'Dua', mee: 'Wiyaa', category: Category.NUMBERS },
  { id: 'n3', indo: 'Tiga', mee: 'Widodo', category: Category.NUMBERS },
  { id: 'n4', indo: 'Empat', mee: 'Wii', category: Category.NUMBERS },
  { id: 'n5', indo: 'Lima', mee: 'Idibii', category: Category.NUMBERS },
  { id: 'n6', indo: 'Enam', mee: 'Benumi', category: Category.NUMBERS },
  { id: 'n7', indo: 'Tujuh', mee: 'Pituwo', category: Category.NUMBERS },
  { id: 'n8', indo: 'Delapan', mee: 'Waguwo', category: Category.NUMBERS },
  { id: 'n9', indo: 'Sembilan', mee: 'Iyee', category: Category.NUMBERS },
  { id: 'n10', indo: 'Sepuluh', mee: 'Gaati', category: Category.NUMBERS },

  // Belasan (11-19)
  { id: 'n11', indo: 'Sebelas', mee: 'Enamagati', category: Category.NUMBERS },
  { id: 'n12', indo: 'Dua belas', mee: 'Wiyamagati', category: Category.NUMBERS },
  { id: 'n13', indo: 'Tiga belas', mee: 'Widomagati', category: Category.NUMBERS },
  { id: 'n14', indo: 'Empat belas', mee: 'Wiimagati', category: Category.NUMBERS },
  { id: 'n15', indo: 'Lima belas', mee: 'Idibiimagati', category: Category.NUMBERS },
  { id: 'n16', indo: 'Enam belas', mee: 'Benumimagati', category: Category.NUMBERS },
  { id: 'n17', indo: 'Tujuh belas', mee: 'Pituwomagati', category: Category.NUMBERS },
  { id: 'n18', indo: 'Delapan belas', mee: 'Waguwomagati', category: Category.NUMBERS },
  { id: 'n19', indo: 'Sembilan belas', mee: 'Iyeegaati', category: Category.NUMBERS },

  // 20-29
  { id: 'n20', indo: 'Dua puluh', mee: 'Mepina', category: Category.NUMBERS },
  { id: 'n21', indo: 'Dua puluh satu', mee: 'Enamamepina', category: Category.NUMBERS },
  { id: 'n22', indo: 'Dua puluh dua', mee: 'Wiyamamepina', category: Category.NUMBERS },
  { id: 'n23', indo: 'Dua puluh tiga', mee: 'Widomamepina', category: Category.NUMBERS },
  { id: 'n24', indo: 'Dua puluh empat', mee: 'Wiimamepina', category: Category.NUMBERS },
  { id: 'n25', indo: 'Dua puluh lima', mee: 'Idibimamepina', category: Category.NUMBERS },
  { id: 'n26', indo: 'Dua puluh enam', mee: 'Benumimamepina', category: Category.NUMBERS },
  { id: 'n27', indo: 'Dua puluh tujuh', mee: 'Pituwomamepina', category: Category.NUMBERS },
  { id: 'n28', indo: 'Dua puluh delapan', mee: 'Waguwomamepina', category: Category.NUMBERS },
  { id: 'n29', indo: 'Dua puluh sembilan', mee: 'Iyeemepina', category: Category.NUMBERS },

  // 30-39
  { id: 'n30', indo: 'Tiga puluh', mee: 'Yokagatii', category: Category.NUMBERS },
  { id: 'n31', indo: 'Tiga puluh satu', mee: 'Enamayokagati', category: Category.NUMBERS },
  { id: 'n32', indo: 'Tiga puluh dua', mee: 'Wiyamayokagati', category: Category.NUMBERS },
  { id: 'n33', indo: 'Tiga puluh tiga', mee: 'Widomayokagati', category: Category.NUMBERS },
  { id: 'n34', indo: 'Tiga puluh empat', mee: 'Wiimayokagati', category: Category.NUMBERS },
  { id: 'n35', indo: 'Tiga puluh lima', mee: 'Idibima yokagati', category: Category.NUMBERS },
  { id: 'n36', indo: 'Tiga puluh enam', mee: 'Benumima yokagati', category: Category.NUMBERS },
  { id: 'n37', indo: 'Tiga puluh tujuh', mee: 'Pituwoma yokagati', category: Category.NUMBERS },
  { id: 'n38', indo: 'Tiga puluh delapan', mee: 'Waguma yokagati', category: Category.NUMBERS },
  { id: 'n39', indo: 'Tiga puluh sembilan', mee: 'Iyeeyokagatii', category: Category.NUMBERS },

  // 40-49
  { id: 'n40', indo: 'Empat puluh', mee: 'Mepiya', category: Category.NUMBERS },
  { id: 'n41', indo: 'Empat puluh satu', mee: 'Enama mepiya', category: Category.NUMBERS },
  { id: 'n42', indo: 'Empat puluh dua', mee: 'Wiyama mepiya', category: Category.NUMBERS },
  { id: 'n43', indo: 'Empat puluh tiga', mee: 'Widoma mepiya', category: Category.NUMBERS },
  { id: 'n44', indo: 'Empat puluh empat', mee: 'Wiima mepiya', category: Category.NUMBERS },
  { id: 'n45', indo: 'Empat puluh lima', mee: 'Idibima mepiya', category: Category.NUMBERS },
  { id: 'n46', indo: 'Empat puluh enam', mee: 'Benumima mepiya', category: Category.NUMBERS },
  { id: 'n47', indo: 'Empat puluh tujuh', mee: 'Pituwoma mepiya', category: Category.NUMBERS },
  { id: 'n48', indo: 'Empat puluh delapan', mee: 'Waguwoma mepiya', category: Category.NUMBERS },
  { id: 'n49', indo: 'Empat puluh sembilan', mee: 'Iyema mepiya', category: Category.NUMBERS },

  // 50-59
  { id: 'n50', indo: 'Lima puluh', mee: 'Gatibeu', category: Category.NUMBERS },
  { id: 'n51', indo: 'Lima puluh satu', mee: 'Enama gatibeu', category: Category.NUMBERS },
  { id: 'n52', indo: 'Lima puluh dua', mee: 'Wiyama gatibeu', category: Category.NUMBERS },
  { id: 'n53', indo: 'Lima puluh tiga', mee: 'Widoma gatibeu', category: Category.NUMBERS },
  { id: 'n54', indo: 'Lima puluh empat', mee: 'Wiima gatibeu', category: Category.NUMBERS },
  { id: 'n55', indo: 'Lima puluh lima', mee: 'Idibima gatibeu', category: Category.NUMBERS },
  { id: 'n56', indo: 'Lima puluh enam', mee: 'Benumima gatibeu', category: Category.NUMBERS },
  { id: 'n57', indo: 'Lima puluh tujuh', mee: 'Pituma gatibeu', category: Category.NUMBERS },
  { id: 'n58', indo: 'Lima puluh delapan', mee: 'Waguma gatibeu', category: Category.NUMBERS },
  { id: 'n59', indo: 'Lima puluh sembilan', mee: 'Iyema gatibeu', category: Category.NUMBERS },

  // 60-69
  { id: 'n60', indo: 'Enam puluh', mee: 'Mekabado', category: Category.NUMBERS },
  { id: 'n61', indo: 'Enam puluh satu', mee: 'Enama mekabado', category: Category.NUMBERS },
  { id: 'n62', indo: 'Enam puluh dua', mee: 'Wiyama mekabado', category: Category.NUMBERS },
  { id: 'n63', indo: 'Enam puluh tiga', mee: 'Widoma mekabado', category: Category.NUMBERS },
  { id: 'n64', indo: 'Enam puluh empat', mee: 'Wiima mekabado', category: Category.NUMBERS },
  { id: 'n65', indo: 'Enam puluh lima', mee: 'Idibima mekabado', category: Category.NUMBERS },
  { id: 'n66', indo: 'Enam puluh enam', mee: 'Benumima mekabado', category: Category.NUMBERS },
  { id: 'n67', indo: 'Enam puluh tujuh', mee: 'Pituwoma mekabado', category: Category.NUMBERS },
  { id: 'n68', indo: 'Enam puluh delapan', mee: 'Waguwoma mekabado', category: Category.NUMBERS },
  { id: 'n69', indo: 'Enam puluh sembilan', mee: 'Iyema mekabado', category: Category.NUMBERS },

  // 70-79
  { id: 'n70', indo: 'Tujuh puluh', mee: 'Mekamiyodaimebado', category: Category.NUMBERS },
  { id: 'n71', indo: 'Tujuh puluh satu', mee: 'Enama miyodaimebado', category: Category.NUMBERS },
  { id: 'n72', indo: 'Tujuh puluh dua', mee: 'Wiyama miyodaimebado', category: Category.NUMBERS },
  { id: 'n73', indo: 'Tujuh puluh tiga', mee: 'Widoma miyodaimebado', category: Category.NUMBERS },
  { id: 'n74', indo: 'Tujuh puluh empat', mee: 'Wiima miyodaimebado', category: Category.NUMBERS },
  { id: 'n75', indo: 'Tujuh puluh lima', mee: 'Idibima miyodaimebado', category: Category.NUMBERS },
  { id: 'n76', indo: 'Tujuh puluh enam', mee: 'Benumima miyodaimebado', category: Category.NUMBERS },
  { id: 'n77', indo: 'Tujuh puluh tujuh', mee: 'Pituwoma miyodaimebado', category: Category.NUMBERS },
  { id: 'n78', indo: 'Tujuh puluh delapan', mee: 'Waguwoma miyodaimebado', category: Category.NUMBERS },
  { id: 'n79', indo: 'Tujuh puluh sembilan', mee: 'Iyemamiyodaimebado', category: Category.NUMBERS },

  // 80-89
  { id: 'n80', indo: 'Delapan puluh', mee: 'Wagubado mepiya', category: Category.NUMBERS },
  { id: 'n81', indo: 'Delapan puluh satu', mee: 'Enama wagubado mepiya', category: Category.NUMBERS },
  { id: 'n82', indo: 'Delapan puluh dua', mee: 'Wiyama wagubado mepiya', category: Category.NUMBERS },
  { id: 'n83', indo: 'Delapan puluh tiga', mee: 'Widoma wagubado mepiya', category: Category.NUMBERS },
  { id: 'n84', indo: 'Delapan puluh empat', mee: 'Wiima wagubado mepiya', category: Category.NUMBERS },
  { id: 'n85', indo: 'Delapan puluh lima', mee: 'Idibima wagubado mepiya', category: Category.NUMBERS },
  { id: 'n86', indo: 'Delapan puluh enam', mee: 'Benumima wagubado mepiya', category: Category.NUMBERS },
  { id: 'n87', indo: 'Delapan puluh tujuh', mee: 'Pituwoma wagubado mepiya', category: Category.NUMBERS },
  { id: 'n88', indo: 'Delapan puluh delapan', mee: 'Waguwoma wagubado mepiya', category: Category.NUMBERS },
  { id: 'n89', indo: 'Delapan puluh sembilan', mee: 'Iyema wagubado mepiya', category: Category.NUMBERS },

  // 90-99
  { id: 'n90', indo: 'Sembilan puluh', mee: 'Iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n91', indo: 'Sembilan puluh satu', mee: 'Enama iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n92', indo: 'Sembilan puluh dua', mee: 'Wiyama iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n93', indo: 'Sembilan puluh tiga', mee: 'Widoma iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n94', indo: 'Sembilan puluh empat', mee: 'Wiima iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n95', indo: 'Sembilan puluh lima', mee: 'Idibima iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n96', indo: 'Sembilan puluh enam', mee: 'Benumima iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n97', indo: 'Sembilan puluh tujuh', mee: 'Pituwoma iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n98', indo: 'Sembilan puluh delapan', mee: 'Waguwoma iyeebado mepiya', category: Category.NUMBERS },
  { id: 'n99', indo: 'Sembilan puluh sembilan', mee: 'Iyema iyeebado mepiya', category: Category.NUMBERS },

  // 100-119
  { id: 'n100', indo: 'Seratus', mee: 'Ogaikabado', category: Category.NUMBERS },
  { id: 'n101', indo: 'Seratus satu', mee: 'Ogaikabadoma Ena', category: Category.NUMBERS },
  { id: 'n102', indo: 'Seratus dua', mee: 'Ogaikabadoma Wiya', category: Category.NUMBERS },
  { id: 'n103', indo: 'Seratus tiga', mee: 'Ogaikabadoma Wido', category: Category.NUMBERS },
  { id: 'n104', indo: 'Seratus empat', mee: 'Ogaikabadoma Wii', category: Category.NUMBERS },
  { id: 'n105', indo: 'Seratus lima', mee: 'Ogaikabadoma Idibi', category: Category.NUMBERS },
  { id: 'n106', indo: 'Seratus enam', mee: 'Ogaikabadoma Benumi', category: Category.NUMBERS },
  { id: 'n107', indo: 'Seratus tujuh', mee: 'Ogaikabadoma Pituwo', category: Category.NUMBERS },
  { id: 'n108', indo: 'Seratus delapan', mee: 'Ogaikabadoma Waguwo', category: Category.NUMBERS },
  { id: 'n109', indo: 'Seratus sembilan', mee: 'Ogaikabadoma Iyee', category: Category.NUMBERS },
  { id: 'n110', indo: 'Seratus sepuluh', mee: 'Ogaikabadoma Gaati', category: Category.NUMBERS },
  { id: 'n111', indo: 'Seratus sebelas', mee: 'Ogaikabadoma Enamagati', category: Category.NUMBERS },
  { id: 'n112', indo: 'Seratus dua belas', mee: 'Ogaikabadoma Wiyamagati', category: Category.NUMBERS },
  { id: 'n113', indo: 'Seratus tiga belas', mee: 'Ogaikabadoma Widomagati', category: Category.NUMBERS },
  { id: 'n114', indo: 'Seratus empat belas', mee: 'Ogaikabadoma Wiimagati', category: Category.NUMBERS },
  { id: 'n115', indo: 'Seratus lima belas', mee: 'Ogaikabadoma Idibiimagati', category: Category.NUMBERS },
  { id: 'n116', indo: 'Seratus enam belas', mee: 'Ogaikabadoma Benumimagati', category: Category.NUMBERS },
  { id: 'n117', indo: 'Seratus tujuh belas', mee: 'Ogaikabadoma Pituwomagati', category: Category.NUMBERS },
  { id: 'n118', indo: 'Seratus delapan belas', mee: 'Ogaikabadoma Waguwomagati', category: Category.NUMBERS },
  { id: 'n119', indo: 'Seratus sembilan belas', mee: 'Ogaikabadoma Iyeegaati', category: Category.NUMBERS },

  // 120-190
  { id: 'n120', indo: 'Seratus dua puluh', mee: 'Ogaikabadoma Mepina', category: Category.NUMBERS },
  { id: 'n121', indo: 'Seratus dua puluh satu', mee: 'Ogaikabadoma Enamamepina', category: Category.NUMBERS },
  { id: 'n122', indo: 'Seratus dua puluh dua', mee: 'Ogaikabadoma Wiyamamepina', category: Category.NUMBERS },
  { id: 'n123', indo: 'Seratus dua puluh tiga', mee: 'Ogaikabadoma Widomamepina', category: Category.NUMBERS },
  { id: 'n124', indo: 'Seratus dua puluh empat', mee: 'Ogaikabadoma Wiimamepina', category: Category.NUMBERS },
  { id: 'n125', indo: 'Seratus dua puluh lima', mee: 'Ogaikabadoma Idibimamepina', category: Category.NUMBERS },
  { id: 'n126', indo: 'Seratus dua puluh enam', mee: 'Ogaikabadoma Benumimamepina', category: Category.NUMBERS },
  { id: 'n127', indo: 'Seratus dua puluh tujuh', mee: 'Ogaikabadoma Pituwomamepina', category: Category.NUMBERS },
  { id: 'n128', indo: 'Seratus dua puluh delapan', mee: 'Ogaikabadoma Waguwomamepina', category: Category.NUMBERS },
  { id: 'n129', indo: 'Seratus dua puluh sembilan', mee: 'Ogaikabadoma Iyemamepina', category: Category.NUMBERS },
  
  { id: 'n130', indo: 'Seratus tiga puluh', mee: 'Ogaikabadoma Yokagati', category: Category.NUMBERS },
  { id: 'n131', indo: 'Seratus tiga puluh satu', mee: 'Ogaikabadoma Enamayokagati', category: Category.NUMBERS },
  { id: 'n132', indo: 'Seratus tiga puluh dua', mee: 'Ogaikabadoma Wiyamayokagati', category: Category.NUMBERS },
  { id: 'n133', indo: 'Seratus tiga puluh tiga', mee: 'Ogaikabadoma Widomayokagati', category: Category.NUMBERS },
  { id: 'n134', indo: 'Seratus tiga puluh empat', mee: 'Ogaikabadoma Wiimayokagati', category: Category.NUMBERS },
  { id: 'n135', indo: 'Seratus tiga puluh lima', mee: 'Ogaikabadoma Idibima yokagati', category: Category.NUMBERS },
  { id: 'n136', indo: 'Seratus tiga puluh enam', mee: 'Ogaikabadoma Benumima yokagati', category: Category.NUMBERS },
  { id: 'n137', indo: 'Seratus tiga puluh tujuh', mee: 'Ogaikabadoma Pituwomayokagati', category: Category.NUMBERS },
  { id: 'n138', indo: 'Seratus tiga puluh delapan', mee: 'Ogaikabadoma Wagumayokagati', category: Category.NUMBERS },
  { id: 'n139', indo: 'Seratus tiga puluh sembilan', mee: 'Ogaikabadoma Iyemayokagati', category: Category.NUMBERS },

  { id: 'n140', indo: 'Seratus empat puluh', mee: 'Ogaikabadoma Wiimamepina', category: Category.NUMBERS },
  { id: 'n150', indo: 'Seratus lima puluh', mee: 'Ogaikabadoma Gatibeu', category: Category.NUMBERS },
  { id: 'n160', indo: 'Seratus enam puluh', mee: 'Ogaikabadoma Mekabado', category: Category.NUMBERS },
  { id: 'n170', indo: 'Seratus tujuh puluh', mee: 'Ogaikabadoma Mekamiyodaimebado', category: Category.NUMBERS },
  { id: 'n180', indo: 'Seratus delapan puluh', mee: 'Ogaikabadoma Wagubado mepiya', category: Category.NUMBERS },
  { id: 'n190', indo: 'Seratus sembilan puluh', mee: 'Ogaikabadoma Iyeebado mepiya', category: Category.NUMBERS },

  // Ratusan (200-900)
  { id: 'n200', indo: 'Dua ratus', mee: 'Ogaikabado Wiya', category: Category.NUMBERS },
  { id: 'n201', indo: 'Dua ratus satu', mee: 'Ogaikabado Wiya doma Ena', category: Category.NUMBERS },
  { id: 'n202', indo: 'Dua ratus dua', mee: 'Ogaikabado Wiya doma Wiya', category: Category.NUMBERS },
  { id: 'n203', indo: 'Dua ratus tiga', mee: 'Ogaikabado Wiya doma Wido', category: Category.NUMBERS },
  { id: 'n204', indo: 'Dua ratus empat', mee: 'Ogaikabado Wiya doma Wii', category: Category.NUMBERS },
  { id: 'n205', indo: 'Dua ratus lima', mee: 'Ogaikabado Wiya doma Idibi', category: Category.NUMBERS },
  { id: 'n206', indo: 'Dua ratus enam', mee: 'Ogaikabado Wiya doma Benumi', category: Category.NUMBERS },
  { id: 'n207', indo: 'Dua ratus tujuh', mee: 'Ogaikabado Wiya doma Pituwo', category: Category.NUMBERS },
  { id: 'n208', indo: 'Dua ratus delapan', mee: 'Ogaikabado Wiya doma Waguwo', category: Category.NUMBERS },
  { id: 'n209', indo: 'Dua ratus sembilan', mee: 'Ogaikabado Wiya doma Iyee', category: Category.NUMBERS },
  
  { id: 'n210', indo: 'Dua ratus sepuluh', mee: 'Ogaikabado Wiya doma Gaati', category: Category.NUMBERS },
  { id: 'n211', indo: 'Dua ratus sebelas', mee: 'Ogaikabado Wiya doma Enamagati', category: Category.NUMBERS },
  { id: 'n212', indo: 'Dua ratus dua belas', mee: 'Ogaikabado Wiya doma Wiyamagati', category: Category.NUMBERS },
  { id: 'n213', indo: 'Dua ratus tiga belas', mee: 'Ogaikabado Wiya doma Widomagati', category: Category.NUMBERS },
  { id: 'n214', indo: 'Dua ratus empat belas', mee: 'Ogaikabado Wiya doma Wiimagati', category: Category.NUMBERS },
  { id: 'n215', indo: 'Dua ratus lima belas', mee: 'Ogaikabado Wiya doma Idibiimagati', category: Category.NUMBERS },
  { id: 'n216', indo: 'Dua ratus enam belas', mee: 'Ogaikabado Wiya doma Benumimagati', category: Category.NUMBERS },
  { id: 'n217', indo: 'Dua ratus tujuh belas', mee: 'Ogaikabado Wiya doma Pituwomagati', category: Category.NUMBERS },
  { id: 'n218', indo: 'Dua ratus delapan belas', mee: 'Ogaikabado Wiya doma Waguwomagati', category: Category.NUMBERS },
  { id: 'n219', indo: 'Dua ratus sembilan belas', mee: 'Ogaikabado Wiya doma Iyeegaati', category: Category.NUMBERS },

  { id: 'n220', indo: 'Dua ratus dua puluh', mee: 'Ogaikabado Wiya doma Mepina', category: Category.NUMBERS },
  { id: 'n221', indo: 'Dua ratus dua puluh satu', mee: 'Ogaikabado Wiya doma Enamamepina', category: Category.NUMBERS },
  { id: 'n222', indo: 'Dua ratus dua puluh dua', mee: 'Ogaikabado Wiya doma Wiyamamepina', category: Category.NUMBERS },
  { id: 'n223', indo: 'Dua ratus dua puluh tiga', mee: 'Ogaikabado Wiya doma Widomamepina', category: Category.NUMBERS },
  { id: 'n224', indo: 'Dua ratus dua puluh empat', mee: 'Ogaikabado Wiya doma Wiimamepina', category: Category.NUMBERS },
  { id: 'n225', indo: 'Dua ratus dua puluh lima', mee: 'Ogaikabado Wiya doma Idibimamepina', category: Category.NUMBERS },
  { id: 'n226', indo: 'Dua ratus dua puluh enam', mee: 'Ogaikabado Wiya doma Benumimamepina', category: Category.NUMBERS },
  { id: 'n227', indo: 'Dua ratus dua puluh tujuh', mee: 'Ogaikabado Wiya doma Pituwomamepina', category: Category.NUMBERS },
  { id: 'n228', indo: 'Dua ratus dua puluh delapan', mee: 'Ogaikabado Wiya doma Waguwomamepina', category: Category.NUMBERS },
  { id: 'n229', indo: 'Dua ratus dua puluh sembilan', mee: 'Ogaikabado Wiya doma Iyemamepina', category: Category.NUMBERS },
  
  { id: 'n230', indo: 'Dua ratus tiga puluh', mee: 'Ogaikabado Wiya doma Yokagati', category: Category.NUMBERS },
  { id: 'n231', indo: 'Dua ratus tiga puluh satu', mee: 'Ogaikabado Wiya doma Enamayokagati', category: Category.NUMBERS },
  { id: 'n232', indo: 'Dua ratus tiga puluh dua', mee: 'Ogaikabado Wiya doma Wiyamayokagati', category: Category.NUMBERS },
  { id: 'n233', indo: 'Dua ratus tiga puluh tiga', mee: 'Ogaikabado Wiya doma Widomayokagati', category: Category.NUMBERS },
  { id: 'n234', indo: 'Dua ratus tiga puluh empat', mee: 'Ogaikabado Wiya doma Wiimayokagati', category: Category.NUMBERS },
  { id: 'n235', indo: 'Dua ratus tiga puluh lima', mee: 'Ogaikabado Wiya doma Idibima yokagati', category: Category.NUMBERS },
  { id: 'n236', indo: 'Dua ratus tiga puluh enam', mee: 'Ogaikabado Wiya doma Benumima yokagati', category: Category.NUMBERS },
  { id: 'n237', indo: 'Dua ratus tiga puluh tujuh', mee: 'Ogaikabado Wiya doma Pituwomayokagati', category: Category.NUMBERS },
  { id: 'n238', indo: 'Dua ratus tiga puluh delapan', mee: 'Ogaikabado Wiya doma Wagumayokagati', category: Category.NUMBERS },
  { id: 'n239', indo: 'Dua ratus tiga puluh sembilan', mee: 'Ogaikabado Wiya doma Iyemayokagati', category: Category.NUMBERS },

  { id: 'n240', indo: 'Dua ratus empat puluh', mee: 'Ogaikabado Wiya doma Wiimamepina', category: Category.NUMBERS },
  { id: 'n250', indo: 'Dua ratus lima puluh', mee: 'Ogaikabado Wiya doma Gatibeu', category: Category.NUMBERS },
  { id: 'n260', indo: 'Dua ratus enam puluh', mee: 'Ogaikabado Wiya doma Mekabado', category: Category.NUMBERS },
  { id: 'n270', indo: 'Dua ratus tujuh puluh', mee: 'Ogaikabado Wiya doma Mekamiyodaimebado', category: Category.NUMBERS },
  { id: 'n280', indo: 'Dua ratus delapan puluh', mee: 'Ogaikabado Wiya doma Wagubado mepiya', category: Category.NUMBERS },
  { id: 'n290', indo: 'Dua ratus sembilan puluh', mee: 'Ogaikabado Wiya doma Iyeebado mepiya', category: Category.NUMBERS },

  { id: 'n300', indo: 'Tiga ratus', mee: 'Ogaikabado Wido', category: Category.NUMBERS },
  { id: 'n400', indo: 'Empat ratus', mee: 'Ogaikabado Wii', category: Category.NUMBERS },
  { id: 'n500', indo: 'Lima ratus', mee: 'Ogaikabado Idibi', category: Category.NUMBERS },
  { id: 'n600', indo: 'Enam ratus', mee: 'Ogaikabado Benumi', category: Category.NUMBERS },
  { id: 'n700', indo: 'Tujuh ratus', mee: 'Ogaikabado Pituwo', category: Category.NUMBERS },
  { id: 'n800', indo: 'Delapan ratus', mee: 'Ogaikabado Waguwo', category: Category.NUMBERS },
  { id: 'n900', indo: 'Sembilan ratus', mee: 'Ogaikabado Iyee', category: Category.NUMBERS },

  // Ribuan & Jutaan
  { id: 'n1000', indo: 'Seribu', mee: 'Gatibeu', category: Category.NUMBERS },
  { id: 'n2000', indo: 'Dua ribu', mee: 'Wiyamagatibeu', category: Category.NUMBERS },
  { id: 'n3000', indo: 'Tiga ribu', mee: 'Widomagatibeu', category: Category.NUMBERS },
  { id: 'n4000', indo: 'Empat ribu', mee: 'Wiimagatibeu', category: Category.NUMBERS },
  { id: 'n5000', indo: 'Lima ribu', mee: 'Idibimagatibeu', category: Category.NUMBERS },
  { id: 'n6000', indo: 'Enam ribu', mee: 'Benumimagatibeu', category: Category.NUMBERS },
  { id: 'n7000', indo: 'Tujuh ribu', mee: 'Pituwomagatibeu', category: Category.NUMBERS },
  { id: 'n8000', indo: 'Delapan ribu', mee: 'Wagumagatibeu', category: Category.NUMBERS },
  { id: 'n9000', indo: 'Sembilan ribu', mee: 'Iyemagatibeu', category: Category.NUMBERS },
  { id: 'n10000', indo: 'Sepuluh ribu', mee: 'Mepiyagatibeu', category: Category.NUMBERS },
  { id: 'n20000', indo: 'Dua puluh ribu', mee: 'Mepinagatibeu', category: Category.NUMBERS },
  { id: 'n100000', indo: 'Seratus ribu', mee: 'Ogaikabado Gatibeu', category: Category.NUMBERS },
  { id: 'n200000', indo: 'Dua ratus ribu', mee: 'Ogaikabado Wiya Gatibeu', category: Category.NUMBERS },
  { id: 'n300000', indo: 'Tiga ratus ribu', mee: 'Ogaikabado Wido Gatibeu', category: Category.NUMBERS },
  { id: 'n400000', indo: 'Empat ratus ribu', mee: 'Ogaikabado Wii Gatibeu', category: Category.NUMBERS },
  { id: 'n500000', indo: 'Lima ratus ribu', mee: 'Ogaikabado Idibi Gatibeu', category: Category.NUMBERS },
  { id: 'n600000', indo: 'Enam ratus ribu', mee: 'Ogaikabado Benumi Gatibeu', category: Category.NUMBERS },
  { id: 'n700000', indo: 'Tujuh ratus ribu', mee: 'Ogaikabado Pituwo Gatibeu', category: Category.NUMBERS },
  { id: 'n800000', indo: 'Delapan ratus ribu', mee: 'Ogaikabado Waguwo Gatibeu', category: Category.NUMBERS },
  { id: 'n900000', indo: 'Sembilan ratus ribu', mee: 'Ogaikabado Iyee Gatibeu', category: Category.NUMBERS },
  { id: 'n1000000', indo: 'Satu juta', mee: 'Gatibeuu', category: Category.NUMBERS },


  // --- COLORS (Warna) ---
  { id: 'c1', indo: 'Hitam', mee: 'Bagee / Pugi', category: Category.COLORS },
  { id: 'c2', indo: 'Putih', mee: 'Dege / Busa', category: Category.COLORS },
  { id: 'c3', indo: 'Merah', mee: 'Taki', category: Category.COLORS },
  { id: 'c4', indo: 'Biru', mee: 'Piku', category: Category.COLORS },
  { id: 'c5', indo: 'Hijau', mee: 'Iyo', category: Category.COLORS },
  { id: 'c6', indo: 'Kuning', mee: 'Ugame', category: Category.COLORS },


  // --- ANIMALS (Hewan) ---
  { id: 'a1', indo: 'Anjing', mee: 'Dodiyoka', category: Category.ANIMALS },
  { id: 'a2', indo: 'Ayam', mee: 'Bedouu', category: Category.ANIMALS },
  { id: 'a3', indo: 'Babi', mee: 'Ekina', category: Category.ANIMALS },
  { id: 'a4', indo: 'Belalang', mee: 'Iyuu', category: Category.ANIMALS },
  { id: 'a5', indo: 'Biawak', mee: 'Soa-soa', category: Category.ANIMALS },
  { id: 'a6', indo: 'Burung', mee: 'Bedo', category: Category.ANIMALS },
  { id: 'a7', indo: 'Cacing', mee: 'Toka', category: Category.ANIMALS },
  { id: 'a8', indo: 'Gajah', mee: 'Gaiii', category: Category.ANIMALS },
  { id: 'a9', indo: 'Ikan', mee: 'Ikane', category: Category.ANIMALS },
  { id: 'a10', indo: 'Katak', mee: 'Dogee', category: Category.ANIMALS },
  { id: 'a11', indo: 'Kambing', mee: 'Kamigi', category: Category.ANIMALS },
  { id: 'a12', indo: 'Kecoa', mee: 'Aju', category: Category.ANIMALS },
  { id: 'a13', indo: 'Kelinci', mee: 'Kedeti', category: Category.ANIMALS },
  { id: 'a14', indo: 'Kelelawar', mee: 'Ditou', category: Category.ANIMALS },
  { id: 'a15', indo: 'Kupu-kupu', mee: 'Bebega', category: Category.ANIMALS },
  { id: 'a16', indo: 'Kucing', mee: 'Pusss', category: Category.ANIMALS },
  { id: 'a17', indo: 'Kuda', mee: 'Kodou', category: Category.ANIMALS },
  { id: 'a18', indo: 'Lalat', mee: 'Pune', category: Category.ANIMALS },
  { id: 'a19', indo: 'Monyet / Kera', mee: 'Kelabou', category: Category.ANIMALS },
  { id: 'a20', indo: 'Nyamuk', mee: 'Dipi', category: Category.ANIMALS },
  { id: 'a21', indo: 'Rusa', mee: 'Buda', category: Category.ANIMALS },
  { id: 'a22', indo: 'Semut merah', mee: 'Ikukah', category: Category.ANIMALS },
  { id: 'a23', indo: 'Singa', mee: 'Dinga', category: Category.ANIMALS },
  { id: 'a24', indo: 'Tawon', mee: 'Ibopune', category: Category.ANIMALS },
  { id: 'a25', indo: 'Tikus', mee: 'Kedei', category: Category.ANIMALS },
  { id: 'a26', indo: 'Ulat', mee: 'Abubo', category: Category.ANIMALS },
  { id: 'a27', indo: 'Ular', mee: 'Jina', category: Category.ANIMALS },
  { id: 'a28', indo: 'Udang', mee: 'Udi', category: Category.ANIMALS },
  { id: 'a29', indo: 'Ekor', mee: 'Puga', category: Category.ANIMALS },


  // --- FRUITS & VEGETABLES (Buah & Sayuran) ---
  { id: 'f1', indo: 'Belimbing', mee: 'Tidapo', category: Category.FRUITS_VEG },
  { id: 'f2', indo: 'Jagung', mee: 'Yokone', category: Category.FRUITS_VEG },
  { id: 'f3', indo: 'Jambu', mee: 'Iyade', category: Category.FRUITS_VEG },
  { id: 'f4', indo: 'Jantung pisang', mee: 'Mapi kegepa', category: Category.FRUITS_VEG },
  { id: 'f5', indo: 'Kacang tanah', mee: 'Kacane', category: Category.FRUITS_VEG },
  { id: 'f6', indo: 'Kangkung', mee: 'Notakau', category: Category.FRUITS_VEG },
  { id: 'f7', indo: 'Kelapa', mee: 'Kedepa', category: Category.FRUITS_VEG },
  { id: 'f8', indo: 'Ketimun', mee: 'Tuda', category: Category.FRUITS_VEG },
  { id: 'f9', indo: 'Labu', mee: 'Rabo', category: Category.FRUITS_VEG },
  { id: 'f10', indo: 'Mangga', mee: 'Magee', category: Category.FRUITS_VEG },
  { id: 'f11', indo: 'Nanas', mee: 'Nenes', category: Category.FRUITS_VEG },
  { id: 'f12', indo: 'Pepaya', mee: 'Mepayai', category: Category.FRUITS_VEG },
  { id: 'f13', indo: 'Pisang', mee: 'Mapi', category: Category.FRUITS_VEG },
  { id: 'f14', indo: 'Terong', mee: 'Kerong', category: Category.FRUITS_VEG },
  { id: 'f15', indo: 'Ubi jalar', mee: 'Nota', category: Category.FRUITS_VEG },
  { id: 'f16', indo: 'Ubi kayu / Singkong', mee: 'Nota piya', category: Category.FRUITS_VEG },
  { id: 'f17', indo: 'Ubi', mee: 'Dugi / Nota', category: Category.FRUITS_VEG },


  // --- OBJECTS (Benda & Barang) ---
  { id: 'o1', indo: 'Air', mee: 'Uwoo', category: Category.OBJECTS },
  { id: 'o2', indo: 'Baju', mee: 'Kagaba', category: Category.OBJECTS },
  { id: 'o3', indo: 'Batu', mee: 'Mogo / Oma', category: Category.OBJECTS },
  { id: 'o4', indo: 'Bola', mee: 'Wagewage', category: Category.OBJECTS },
  { id: 'o5', indo: 'Celana', mee: 'Kagaba', category: Category.OBJECTS },
  { id: 'o6', indo: 'Daun', mee: 'Piyaiyee', category: Category.OBJECTS },
  { id: 'o7', indo: 'Duri', mee: 'Dogo duri', category: Category.OBJECTS },
  { id: 'o8', indo: 'Jalan', mee: 'Ita', category: Category.OBJECTS },
  { id: 'o9', indo: 'Jendela', mee: 'Awe', category: Category.OBJECTS },
  { id: 'o10', indo: 'Kayu', mee: 'Piya gekita', category: Category.OBJECTS },
  { id: 'o11', indo: 'Kursi', mee: 'Animakaida', category: Category.OBJECTS },
  { id: 'o12', indo: 'Lampu', mee: 'Pito', category: Category.OBJECTS },
  { id: 'o13', indo: 'Lemari', mee: 'Peti', category: Category.OBJECTS },
  { id: 'o14', indo: 'Meja', mee: 'Makida', category: Category.OBJECTS },
  { id: 'o15', indo: 'Mobil', mee: 'Owayago koma', category: Category.OBJECTS },
  { id: 'o16', indo: 'Motor', mee: 'Koma', category: Category.OBJECTS },
  { id: 'o17', indo: 'Palu', mee: 'Yadau', category: Category.OBJECTS },
  { id: 'o18', indo: 'Piring', mee: 'Katagai', category: Category.OBJECTS },
  { id: 'o19', indo: 'Pisau', mee: 'Ekegei', category: Category.OBJECTS },
  { id: 'o20', indo: 'Pintu', mee: 'Damo', category: Category.OBJECTS },
  { id: 'o21', indo: 'Rumah', mee: 'Owa / Owaa / Ee', category: Category.OBJECTS },
  { id: 'o22', indo: 'Rumput', mee: 'Booo', category: Category.OBJECTS },
  { id: 'o23', indo: 'Sapu', mee: 'Deii', category: Category.OBJECTS },
  { id: 'o24', indo: 'Sekolah', mee: 'Topetaida', category: Category.OBJECTS },
  { id: 'o25', indo: 'Tali', mee: 'Nolon', category: Category.OBJECTS },
  { id: 'o26', indo: 'Tas', mee: 'Agiya', category: Category.OBJECTS },
  { id: 'o27', indo: 'Kamar / WC', mee: 'Baa Kaboo', category: Category.OBJECTS },
  { id: 'o28', indo: 'Toples', mee: 'Gau', category: Category.OBJECTS },
  { id: 'o29', indo: 'Uang', mee: 'Megee', category: Category.OBJECTS },
  { id: 'o30', indo: 'Obat', mee: 'Obagi', category: Category.OBJECTS },
  { id: 'o31', indo: 'Api unggun', mee: 'Apii kiya', category: Category.OBJECTS },
  { id: 'o32', indo: 'Sarang', mee: 'Geka', category: Category.OBJECTS },
  { id: 'o33', indo: 'Api', mee: 'Apii', category: Category.OBJECTS },
  { id: 'o34', indo: 'Pasir', mee: 'Kunu', category: Category.OBJECTS },
  { id: 'o35', indo: 'Lumpur', mee: 'Peba', category: Category.OBJECTS },
  { id: 'o36', indo: 'Kotoran', mee: 'Yimu', category: Category.OBJECTS },


  // --- NATURE & TIME (Alam & Waktu) ---
  { id: 'nt1', indo: 'Panas', mee: 'Gobii', category: Category.NATURE },
  { id: 'nt2', indo: 'Dingin', mee: 'Oo', category: Category.NATURE },
  { id: 'nt3', indo: 'Pagi', mee: 'Abata', category: Category.NATURE },
  { id: 'nt4', indo: 'Siang', mee: 'Agapi', category: Category.NATURE },
  { id: 'nt5', indo: 'Malam', mee: 'Wanee', category: Category.NATURE },
  { id: 'nt6', indo: 'Kemarin', mee: 'Geto', category: Category.NATURE },
  { id: 'nt7', indo: 'Hari ini', mee: 'Ito nago', category: Category.NATURE },
  { id: 'nt8', indo: 'Besok', mee: 'Aweeta', category: Category.NATURE },
  { id: 'nt9', indo: 'Pagi subuh', mee: 'Abata bedo mana / Abata digi', category: Category.NATURE },
  { id: 'nt10', indo: 'Hujan', mee: 'Edi', category: Category.NATURE },
  { id: 'nt11', indo: 'Gunung', mee: 'Diimi', category: Category.NATURE },
  { id: 'nt12', indo: 'Tanjung', mee: 'Diimi pugaa', category: Category.NATURE },
  { id: 'nt13', indo: 'Angin', mee: 'Bou', category: Category.NATURE },
  { id: 'nt14', indo: 'Matahari', mee: 'Meuka / Keno', category: Category.NATURE },
  { id: 'nt15', indo: 'Bulan (rembulan)', mee: 'Ago', category: Category.NATURE },
  { id: 'nt16', indo: 'Langit', mee: 'Epoo', category: Category.NATURE },
  { id: 'nt17', indo: 'Bumi', mee: 'Magaa', category: Category.NATURE },
  { id: 'nt18', indo: 'Hutan', mee: 'Weya', category: Category.NATURE },
  { id: 'nt19', indo: 'Danau', mee: 'Paniai', category: Category.NATURE },
  { id: 'nt20', indo: 'Sungai', mee: 'Uwoo goo', category: Category.NATURE },
  { id: 'nt21', indo: 'Bintang', mee: 'Okadee', category: Category.NATURE },
  { id: 'nt22', indo: 'Awan', mee: 'Sinu', category: Category.NATURE },
  { id: 'nt23', indo: 'Petir', mee: 'Apii keno', category: Category.NATURE },
  { id: 'nt24', indo: 'Cahaya', mee: 'Keno pigi', category: Category.NATURE },
  { id: 'nt25', indo: 'Gelap', mee: 'Nage', category: Category.NATURE },
  { id: 'nt26', indo: 'Tanah', mee: 'Magaa wii', category: Category.NATURE },
  { id: 'nt27', indo: 'Kebun', mee: 'Bugi / Amaa', category: Category.NATURE },
  { id: 'nt28', indo: 'Muara kali', mee: 'Wakei bado', category: Category.NATURE },
  { id: 'nt29', indo: 'Puncak', mee: 'Bagoud', category: Category.NATURE },


  // --- PEOPLE, FAMILY & BODY (Orang, Keluarga & Tubuh) ---
  { id: 'p1', indo: 'Saya', mee: 'Ani / Anisaya', category: Category.PEOPLE },
  { id: 'p2', indo: 'Kamu', mee: 'Akii', category: Category.PEOPLE },
  { id: 'p3', indo: 'Kami / Kita', mee: 'Inii', category: Category.PEOPLE },
  { id: 'p4', indo: 'Dia', mee: 'Okai', category: Category.PEOPLE },
  { id: 'p5', indo: 'Mereka', mee: 'Okeii', category: Category.PEOPLE },
  { id: 'p6', indo: 'Orang', mee: 'Mee', category: Category.PEOPLE },
  { id: 'p34', indo: 'Manusia', mee: 'Mee', category: Category.PEOPLE },
  { id: 'p7', indo: 'Laki-laki', mee: 'Yame', category: Category.PEOPLE },
  { id: 'p8', indo: 'Perempuan', mee: 'Yagamo', category: Category.PEOPLE },
  { id: 'p9', indo: 'Ayah / Bapa', mee: 'Naita / Naitai', category: Category.PEOPLE },
  { id: 'p10', indo: 'Ibu / Mama', mee: 'Noukau / Nouka', category: Category.PEOPLE },
  { id: 'p11', indo: 'Anak-anak', mee: 'Yokaidoo', category: Category.PEOPLE },
  { id: 'p12', indo: 'Anak kecil', mee: 'Yoka dabaa', category: Category.PEOPLE },
  { id: 'p13', indo: 'Nama', mee: 'Ekaa', category: Category.PEOPLE },
  { id: 'p14', indo: 'Om / Paman', mee: 'Naama / Yaya / Noukai aikame / Weanekame', category: Category.PEOPLE },
  { id: 'p15', indo: 'Sepupu', mee: 'None', category: Category.PEOPLE },
  { id: 'p16', indo: 'Tante / Aba', mee: 'Aniokaa / Naitai panekame', category: Category.PEOPLE },
  { id: 'p17', indo: 'Bapa ade', mee: 'Naitai weneka', category: Category.PEOPLE },
  { id: 'p18', indo: 'Bapa tua', mee: 'Naitai aikame', category: Category.PEOPLE },
  { id: 'p19', indo: 'Adik kakak', mee: 'Inii keneka', category: Category.PEOPLE },
  { id: 'p20', indo: 'Adik', mee: 'Anii weneka', category: Category.PEOPLE },
  { id: 'p21', indo: 'Kakak laki-laki', mee: 'Nauwai', category: Category.PEOPLE },
  { id: 'p22', indo: 'Kakak perempuan', mee: 'Anibai', category: Category.PEOPLE },
  { id: 'p23', indo: 'Ipar (laki-laki/perempuan)', mee: 'Anigeka', category: Category.PEOPLE },
  { id: 'p24', indo: 'Bapak / Mama mertua', mee: 'Anibaka', category: Category.PEOPLE },
  { id: 'p25', indo: 'Orang gila', mee: 'Dimibeu', category: Category.PEOPLE },
  { id: 'p26', indo: 'Kakek', mee: 'Tata', category: Category.PEOPLE },
  { id: 'p27', indo: 'Nenek', mee: 'Nana', category: Category.PEOPLE },
  { id: 'p28', indo: 'Suami', mee: 'Tabo', category: Category.PEOPLE },
  { id: 'p29', indo: 'Istri', mee: 'Nawi', category: Category.PEOPLE },
  { id: 'p30', indo: 'Teman', mee: 'Nogei', category: Category.PEOPLE },
  { id: 'p31', indo: 'Musuh', mee: 'Eya awee keta', category: Category.PEOPLE },
  { id: 'p32', indo: 'Keluarga', mee: 'Ita mee / Tuma', category: Category.PEOPLE },
  { id: 'p33', indo: 'Dokter', mee: 'Obagi agiya', category: Category.PEOPLE },
  { id: 'p35', indo: 'Setan', mee: 'Eniyaa', category: Category.PEOPLE },
  { id: 'p36', indo: 'Pengemis', mee: 'Diime', category: Category.PEOPLE },
  { id: 'p37', indo: 'Perampok', mee: 'Oma', category: Category.PEOPLE },
  { id: 'p38', indo: 'Pencuri', mee: 'Bagee', category: Category.PEOPLE },
  { id: 'p39', indo: 'Penjahat', mee: 'Peu bagee', category: Category.PEOPLE },
  { id: 'p40', indo: 'Bangsa / Suku', mee: 'Oang / Oangii / Aka', category: Category.PEOPLE },
  { id: 'p41', indo: 'Marga / Klan', mee: 'Bage', category: Category.PEOPLE },
  { id: 'p42', indo: 'Pemuda', mee: 'Bagitago', category: Category.PEOPLE },
  
  // Body Parts included in People category
  { id: 'pb1', indo: 'Sakit kepala', mee: 'Dagi didi', category: Category.PEOPLE },
  { id: 'pb2', indo: 'Kepala', mee: 'Mogo', category: Category.PEOPLE },
  { id: 'pb3', indo: 'Rambut', mee: 'Mogo yawi', category: Category.PEOPLE },
  { id: 'pb4', indo: 'Mata', mee: 'Kene mee', category: Category.PEOPLE },
  { id: 'pb5', indo: 'Hidung', mee: 'Digi', category: Category.PEOPLE },
  { id: 'pb6', indo: 'Telinga', mee: 'Tene mee', category: Category.PEOPLE },
  { id: 'pb7', indo: 'Mulut', mee: 'Uyaa mee', category: Category.PEOPLE },
  { id: 'pb8', indo: 'Tangan', mee: 'Ayaa', category: Category.PEOPLE },
  { id: 'pb9', indo: 'Kaki', mee: 'Aake / Bado', category: Category.PEOPLE },
  { id: 'pb10', indo: 'Hati', mee: 'Yawi mee', category: Category.PEOPLE },
  { id: 'pb11', indo: 'Darah', mee: 'Ekou', category: Category.PEOPLE },
  { id: 'pb12', indo: 'Tulang', mee: 'Pane', category: Category.PEOPLE },
  { id: 'pb13', indo: 'Pepe (Alat kelamin wanita)', mee: 'Tugi', category: Category.PEOPLE },
  { id: 'pb14', indo: 'Lolo (Alat kelamin pria)', mee: 'Koti / Paa', category: Category.PEOPLE },
  { id: 'pb15', indo: 'Kaki (bunyi langkah)', mee: 'Bado nekii', category: Category.PEOPLE },
  { id: 'pb16', indo: 'Kaki & tangan', mee: 'Gane bado', category: Category.PEOPLE },
  { id: 'pb17', indo: 'Kaki kiri', mee: 'Aka bado', category: Category.PEOPLE },
  { id: 'pb18', indo: 'Kulit', mee: 'Bage / Buna', category: Category.PEOPLE },
  { id: 'pb19', indo: 'Sendi', mee: 'Kagu', category: Category.PEOPLE },
  { id: 'pb20', indo: 'Lutut', mee: 'Bago', category: Category.PEOPLE },


  // --- BASICS (Kata Dasar & Ucapan Sehari-hari) ---
  { id: 'b1', indo: 'Ini', mee: 'Kiii', category: Category.BASICS },
  { id: 'b2', indo: 'Itu', mee: 'Ikou / Manako', category: Category.BASICS },
  { id: 'b3', indo: 'Apa', mee: 'Maagiyoo', category: Category.BASICS },
  { id: 'b4', indo: 'Kapan', mee: 'Menaa', category: Category.BASICS },
  { id: 'b5', indo: 'Di mana', mee: 'Kaiyaa', category: Category.BASICS },
  { id: 'b6', indo: 'Yang mana', mee: 'Kawikaaki / Kawokaa kou', category: Category.BASICS },
  { id: 'b7', indo: 'Siapa', mee: 'Meime', category: Category.BASICS },
  { id: 'b8', indo: 'Mengapa / Kenapa', mee: 'Maagiyokaa', category: Category.BASICS },
  { id: 'b9', indo: 'Bagaimana', mee: 'Kadanii', category: Category.BASICS },
  { id: 'b10', indo: 'Ya / Iya', mee: 'Iii', category: Category.BASICS },
  { id: 'b11', indo: 'Tidak', mee: 'Beu', category: Category.BASICS },
  { id: 'b12', indo: 'Barangkali / Mungkin', mee: 'Ikoukeii / Yuwa', category: Category.BASICS },
  { id: 'b13', indo: 'Kira-kira', mee: 'Yuwa', category: Category.BASICS },
  { id: 'b14', indo: 'Semua', mee: 'Idimaa', category: Category.BASICS },
  { id: 'b15', indo: 'Kalau / Jika', mee: 'Koudanite', category: Category.BASICS },
  { id: 'b16', indo: 'Lebih lagi', mee: 'Inooma', category: Category.BASICS },
  { id: 'b17', indo: 'Sangat sekali', mee: 'Makodo', category: Category.BASICS },
  { id: 'b18', indo: 'Dari mana', mee: 'Kaiya makee', category: Category.BASICS },
  { id: 'b19', indo: 'Ke mana', mee: 'Kaiyaoo / Kaya uwetee', category: Category.BASICS },
  { id: 'b20', indo: 'Sekarang', mee: 'Itokou', category: Category.BASICS },
  { id: 'b21', indo: 'Belum', mee: 'Beu', category: Category.BASICS },
  { id: 'b22', indo: 'Karena', mee: 'Kouya', category: Category.BASICS },
  { id: 'b23', indo: 'Tetapi', mee: 'Kodoya', category: Category.BASICS },
  { id: 'b24', indo: 'Di sini', mee: 'Kiiya', category: Category.BASICS },
  { id: 'b25', indo: 'Baik', mee: 'Enaao', category: Category.BASICS },
  { id: 'b26', indo: 'Jelek', mee: 'Peu', category: Category.BASICS },
  { id: 'b27', indo: 'Betul / Benar', mee: 'Maakodo', category: Category.BASICS },
  { id: 'b28', indo: 'Indah / Cantik', mee: 'Enauto', category: Category.BASICS },
  { id: 'b29', indo: 'Besar', mee: 'Ibo / Akii', category: Category.BASICS },
  { id: 'b30', indo: 'Kecil', mee: 'Daaba', category: Category.BASICS },
  { id: 'b31', indo: 'Banyak', mee: 'Uminaa', category: Category.BASICS },
  { id: 'b32', indo: 'Sedikit', mee: 'Wiyatoo', category: Category.BASICS },
  { id: 'b33', indo: 'Sama', mee: 'Enadani', category: Category.BASICS },
  { id: 'b34', indo: 'Bisa', mee: 'Keitimake', category: Category.BASICS },
  { id: 'b35', indo: 'Punya', mee: 'Ewaa', category: Category.BASICS },
  { id: 'b36', indo: 'Ada', mee: 'Topa', category: Category.BASICS },
  { id: 'b37', indo: 'Bekas', mee: 'Dogaa', category: Category.BASICS },
  { id: 'b38', indo: 'Jangan', mee: 'Tekeitai', category: Category.BASICS },
  { id: 'b39', indo: 'Pergi / Berjalan', mee: 'Uwii / Uwii berangka', category: Category.BASICS },
  { id: 'b40', indo: 'Datang', mee: 'Meii', category: Category.BASICS },
  { id: 'b41', indo: 'Berjalan', mee: 'Ita uwi', category: Category.BASICS },
  { id: 'b42', indo: 'Bicara', mee: 'Manawegai', category: Category.BASICS },
  { id: 'b43', indo: 'Hilang', mee: 'Igaii', category: Category.BASICS },
  { id: 'b44', indo: 'Lihat', mee: 'Dou', category: Category.BASICS },
  { id: 'b45', indo: 'Mengerti', mee: 'Gaai', category: Category.BASICS },
  { id: 'b46', indo: 'Makan', mee: 'Naii', category: Category.BASICS },
  { id: 'b47', indo: 'Minum', mee: 'Uwoo nai', category: Category.BASICS },
  { id: 'b48', indo: 'Dengar', mee: 'Yuwii', category: Category.BASICS },
  { id: 'b49', indo: 'Tahu', mee: 'Epi', category: Category.BASICS },
  { id: 'b50', indo: 'Memberi / Kasih', mee: 'Menii', category: Category.BASICS },
  { id: 'b51', indo: 'Suka / Mau', mee: 'Ide', category: Category.BASICS },
  { id: 'b52', indo: 'Cinta / Pacar', mee: 'Inai ide', category: Category.BASICS },
  { id: 'b53', indo: 'Pikir', mee: 'Dimigai', category: Category.BASICS },
  { id: 'b54', indo: 'Membuat', mee: 'Keitai', category: Category.BASICS },
  { id: 'b55', indo: 'Tidur', mee: 'Uno umii', category: Category.BASICS },
  { id: 'b56', indo: 'Duduk', mee: 'Animakai', category: Category.BASICS },
  { id: 'b57', indo: 'Potong', mee: 'Duwai', category: Category.BASICS },
  { id: 'b58', indo: 'Beli', mee: 'Edai', category: Category.BASICS },
  { id: 'b59', indo: 'Berhenti', mee: 'Ee duwai', category: Category.BASICS },
  { id: 'b60', indo: 'Jauh', mee: 'Potoo', category: Category.BASICS },
  { id: 'b61', indo: 'Dekat', mee: 'Kapaa', category: Category.BASICS },
  { id: 'b62', indo: 'Kanan', mee: 'Etikatoo', category: Category.BASICS },
  { id: 'b63', indo: 'Kiri', mee: 'Akatoo', category: Category.BASICS },
  { id: 'b64', indo: 'Baru', mee: 'Iyaa', category: Category.BASICS },
  { id: 'b65', indo: 'Tua', mee: 'Adama', category: Category.BASICS },
  { id: 'b66', indo: 'Panjang', mee: 'Woyaa', category: Category.BASICS },
  { id: 'b67', indo: 'Pendek', mee: 'Pinii', category: Category.BASICS },
  { id: 'b68', indo: 'Murah', mee: 'Adeka daba', category: Category.BASICS },
  { id: 'b69', indo: 'Mahal', mee: 'Adeka ibo', category: Category.BASICS },
  { id: 'b70', indo: 'Atas', mee: 'Wadou', category: Category.BASICS },
  { id: 'b71', indo: 'Bawah', mee: 'Miyou', category: Category.BASICS },
  { id: 'b72', indo: 'Bawa', mee: 'Dokii', category: Category.BASICS },
  { id: 'b73', indo: 'Lapar', mee: 'Igapu', category: Category.BASICS },
  { id: 'b74', indo: 'Bahagia / Gembira', mee: 'Ideide', category: Category.BASICS },
  { id: 'b75', indo: 'Sakit', mee: 'Didii', category: Category.BASICS },
  { id: 'b76', indo: 'Maaf', mee: 'Ipanayaikai', category: Category.BASICS },
  { id: 'b77', indo: 'Apa kabar', mee: 'Kawedani bidaa beu?', category: Category.BASICS },
  { id: 'b78', indo: 'Berapa', mee: 'Magoo', category: Category.BASICS },
  { id: 'b79', indo: 'Silakan', mee: 'Naaketiyawi', category: Category.BASICS },
  { id: 'b80', indo: 'Terima kasih', mee: 'Idee', category: Category.BASICS },
  { id: 'b81', indo: 'Selamat jalan', mee: 'Koya uwiii', category: Category.BASICS },
  { id: 'b82', indo: 'Mentah', mee: 'Epipode beu / Iyaa', category: Category.BASICS },
  { id: 'b83', indo: 'Muntah', mee: 'Edii', category: Category.BASICS },
  { id: 'b84', indo: 'Ingat', mee: 'Gage', category: Category.BASICS },
  { id: 'b85', indo: 'Kisah / Cerita', mee: 'Tikaika keitita', category: Category.BASICS },
  { id: 'b86', indo: 'Sedih', mee: 'Kogaa', category: Category.BASICS },
  { id: 'b87', indo: 'Bangun', mee: 'Anigou / Bagamo', category: Category.BASICS },
  { id: 'b88', indo: 'Bekerja', mee: 'Awaago', category: Category.BASICS },
  { id: 'b89', indo: 'Belajar', mee: 'Dilago', category: Category.BASICS },
  { id: 'b90', indo: 'Berdiri', mee: 'Tenge', category: Category.BASICS },
  { id: 'b91', indo: 'Bilang', mee: 'Igai', category: Category.BASICS },
  { id: 'b92', indo: 'Cepat', mee: 'Reebo piga', category: Category.BASICS },
  { id: 'b93', indo: 'Kuat', mee: 'Teka', category: Category.BASICS },
  { id: 'b94', indo: 'Lambat', mee: 'Meegoo wiya', category: Category.BASICS },
  { id: 'b95', indo: 'Lari', mee: 'Reebo', category: Category.BASICS },
  { id: 'b96', indo: 'Lemah', mee: 'Teka wiya', category: Category.BASICS },
  { id: 'b97', indo: 'Marah', mee: 'Eya awee', category: Category.BASICS },
  { id: 'b98', indo: 'Menangis', mee: 'Wee', category: Category.BASICS },
  { id: 'b99', indo: 'Salah', mee: 'Deya kapa', category: Category.BASICS },
  { id: 'b100', indo: 'Takut', mee: 'Diyo', category: Category.BASICS },
  { id: 'b101', indo: 'Tertawa', mee: 'Koo', category: Category.BASICS },
  { id: 'b102', indo: 'Mandi', mee: 'Uwo wii', category: Category.BASICS },
  { id: 'b103', indo: 'Masak', mee: 'Gaa / Naii gaa', category: Category.BASICS },
  { id: 'b104', indo: 'Cuci', mee: 'Waii', category: Category.BASICS },
  { id: 'b105', indo: 'Menulis', mee: 'Gaine', category: Category.BASICS },
  { id: 'b106', indo: 'Membaca', mee: 'Gaine dou', category: Category.BASICS },
  { id: 'b108', indo: 'Dimana / Kemana', mee: 'Kaiyaa / Kaiyaoo', category: Category.BASICS },
  { id: 'b109', indo: 'Apa ini?', mee: 'Kii ko', category: Category.BASICS },
  { id: 'b110', indo: 'Jenis / Sesuatu', mee: 'Aka', category: Category.BASICS },
  { id: 'b111', indo: 'Tinggi', mee: 'Bago', category: Category.BASICS },
  { id: 'b112', indo: 'Menjadi', mee: 'Bagoo', category: Category.BASICS },
  { id: 'b113', indo: 'Mengikut', mee: 'Ani i', category: Category.BASICS },
  { id: 'b114', indo: 'Akhiran penegasan arti', mee: '-ii / -koo / -yaa', category: Category.BASICS },
];
